package com.qx.io.ssl.outbound;

import javax.net.ssl.SSLEngine;
import javax.net.ssl.SSLEngineResult;
import javax.net.ssl.SSLEngineResult.Status;
import javax.net.ssl.SSLException;

/**
 * Just flush bytes, but do not require re-launching 
 * unsafeWrap after that
 * 
 * 
 */
public class Closing extends SSL_Outbound.Mode {

	public Closing(SSL_Outbound outbound) {
		outbound.super();
	}

	
	@Override
	public String declare() {
		return "is closing...";
	}
	
	
	@Override
	public void run(SSL_Outbound.Process process) {

		
		SSLEngine engine = getEngine();
		
		/*
		 * Closing this side of the engine
		 */
		engine.closeOutbound();


		/* wrapping */
		try {
			boolean isWrapCompleted = false;
			while(!isWrapCompleted) {

				/*
				 * (JAVA doc) states that:
				 * 
				 * In all cases, closure handshake messages are generated by the engine, and
				 * wrap() should be repeatedly called until the resulting SSLEngineResult's
				 * status returns "CLOSED", or isOutboundDone() returns true.
				 * 
				 */
				/* wrapping */
				SSLEngineResult result = getEngine().wrap(getApplicationBuffer(), getNetworkBuffer());

				if(isVerbose()) {
					System.out.println(getName()+": "+result);
				}

				// end point listening to result for updating phase
				getEndpoint().onResult(result);

				if(result.getStatus()==Status.CLOSED || engine.isOutboundDone() || result.bytesProduced()==0) {
					isWrapCompleted = true;
				}
			}

			/*
			 * All data obtained from the wrap() method should be sent to the peer.
			 */
			process.mode = flush();
		}
		catch (SSLException e) {
			e.printStackTrace();

			// stop here, with no callback
			process.isRunning = false;
		}
	}
}
